import rtconfig
Import('RTT_ROOT')
from building import *

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.
src = Glob('*.c')
path = [cwd]

group = DefineGroup('application', src, depend = [], CPPPATH = path)

Return('group')
