import rtconfig
Import('RTT_ROOT')
from building import *

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.
# src = Split("""
# CMSIS/ST/STM32F4xx/Source/Templates/system_stm32f4xx.c
# """)

# src += Glob('STM32F4xx_StdPeriph_Driver/src/*.c')
src = Glob('driverlib/MSP432P4xx/*.c')


#add for startup script 
# if rtconfig.CROSS_TOOL == 'gcc':
     # src = src + ['CMSIS/ST/STM32F4xx/Source/Templates/gcc_ride7/startup_stm32f4xx.s']
# elif rtconfig.CROSS_TOOL == 'keil':
     # src = src + ['CMSIS/ST/STM32F4xx/Source/Templates/arm/startup_stm32f4xx.s']
# elif rtconfig.CROSS_TOOL == 'iar':
    # src = src + ['CMSIS/CM3/DeviceSupport/ST/STM32F10x/startup/iar/' + startup_scripts[rtconfig.STM32_TYPE]]

# path = [cwd + '/STM32F4xx_StdPeriph_Driver/inc', 
    # cwd + '/CMSIS/ST/STM32F4xx/Include',
    # cwd + '/CMSIS/Include']

# CPPDEFINES = ['USE_STDPERIPH_DRIVER', rtconfig.STM32_TYPE]
# CPPDEFINES = ['USE_STDPERIPH_DRIVER']

path = [cwd + r'/inc', cwd + r'/inc/CMSIS', cwd + r'/driverlib/MSP432P4xx']

CPPDEFINES = ['uint_fast8_t=uint8_t', 'uint_fast16_t=uint16_t',
              'uint_fast32_t=uint32_t', 'uint_fast64_t=uint64_t',
              'uint_least32_t=uint32_t']

group = DefineGroup('msp432_driverlib', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')
