import rtconfig
Import('RTT_ROOT')
from building import *

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.
paho_mqtt_path = os.path.join(cwd, "paho-mqtt")
zephyr_mqtt_path = os.path.join(cwd, "zephyr-mqtt")

# src = Glob(paho_mqtt_path + "/*.c")
src = Glob(zephyr_mqtt_path + "/*.c")

path = [cwd + '/include']

group = DefineGroup('paho-mqtt-rtthread', src, depend = ['RT_USING_PAHOMQTT_RTTHREAD'], CPPPATH = path)

Return('group')
